// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import "encoding/json"

type car struct {
	ID string `json:"id"`
}

type Car struct {
	ID string `json:"id"`
}

func (body *Car) UnmarshalJSON(data []byte) error {
	var value car
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID

	return nil
}

func (body Car) Validate() error {
	return nil
}
