// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import (
	"encoding/json"
	"fmt"
	validation "github.com/go-ozzo/ozzo-validation/v4"
)

type postCarsApplicationJsonRequestBody struct {
	Test *string `json:"test"`
}

type PostCarsApplicationJsonRequestBody struct {
	Test string `json:"test"`
}

func (body *PostCarsApplicationJsonRequestBody) UnmarshalJSON(data []byte) error {
	var value postCarsApplicationJsonRequestBody
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Test == nil {
		return fmt.Errorf("test is required")
	}

	body.Test = *value.Test

	return nil
}
func (body PostCarsApplicationJsonRequestBody) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.Test, validation.Required, validation.RuneLength(10, 0)))
}

type postCarsRequestBody struct {
	Test *string `json:"test"`
}

type PostCarsRequestBody struct {
	Test string `json:"test"`
}

func (body *PostCarsRequestBody) UnmarshalJSON(data []byte) error {
	var value postCarsRequestBody
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	if value.Test == nil {
		return fmt.Errorf("test is required")
	}

	body.Test = *value.Test

	return nil
}
func (body PostCarsRequestBody) Validate() error {
	return validation.ValidateStruct(&body,
		validation.Field(&body.Test, validation.Required, validation.RuneLength(10, 0)))
}
