// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import "encoding/json"

type car struct {
	ID    string `json:"id"`
	Wheel Wheel  `json:"wheel"`
}

type Car struct {
	ID    string `json:"id"`
	Wheel Wheel  `json:"wheel"`
}

func (body *Car) UnmarshalJSON(data []byte) error {
	var value car
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID
	body.Wheel = value.Wheel

	return nil
}

func (body Car) Validate() error {
	return nil
}

type wheel struct {
	ID string `json:"id"`
}

type Wheel struct {
	ID string `json:"id"`
}

func (body *Wheel) UnmarshalJSON(data []byte) error {
	var value wheel
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID

	return nil
}

func (body Wheel) Validate() error {
	return nil
}
