// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import "encoding/json"

type carResponseApplicationjson struct {
	ID string `json:"id"`
}

type CarResponseApplicationjson struct {
	ID string `json:"id"`
}

func (body *CarResponseApplicationjson) UnmarshalJSON(data []byte) error {
	var value carResponseApplicationjson
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID

	return nil
}
func (body CarResponseApplicationjson) Validate() error {
	return nil
}

type carResponseApplicationxml struct {
	ID string `json:"id"`
}

type CarResponseApplicationxml struct {
	ID string `json:"id"`
}

func (body *CarResponseApplicationxml) UnmarshalJSON(data []byte) error {
	var value carResponseApplicationxml
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID

	return nil
}
func (body CarResponseApplicationxml) Validate() error {
	return nil
}
