// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import (
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	v5 "github.com/go-chi/chi/v5"
	"net/http"
)

type Hooks struct {
	RequestSecurityParseFailed    func(*http.Request, string, RequestProcessingResult)
	RequestSecurityParseCompleted func(*http.Request, string)
	RequestSecurityCheckFailed    func(*http.Request, string, string, RequestProcessingResult)
	RequestSecurityCheckCompleted func(*http.Request, string, string)
	RequestBodyUnmarshalFailed    func(*http.Request, string, RequestProcessingResult)
	RequestHeaderParseFailed      func(*http.Request, string, string, RequestProcessingResult)
	RequestPathParseFailed        func(*http.Request, string, string, RequestProcessingResult)
	RequestQueryParseFailed       func(*http.Request, string, string, RequestProcessingResult)
	RequestBodyValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestHeaderValidationFailed func(*http.Request, string, RequestProcessingResult)
	RequestPathValidationFailed   func(*http.Request, string, RequestProcessingResult)
	RequestQueryValidationFailed  func(*http.Request, string, RequestProcessingResult)
	RequestBodyUnmarshalCompleted func(*http.Request, string)
	RequestHeaderParseCompleted   func(*http.Request, string)
	RequestPathParseCompleted     func(*http.Request, string)
	RequestQueryParseCompleted    func(*http.Request, string)
	RequestParseCompleted         func(*http.Request, string)
	RequestProcessingCompleted    func(*http.Request, string)
	RequestRedirectStarted        func(*http.Request, string, string)
	ResponseBodyMarshalCompleted  func(*http.Request, string)
	ResponseBodyWriteCompleted    func(*http.Request, string, int)
	ResponseBodyMarshalFailed     func(http.ResponseWriter, *http.Request, string, error)
	ResponseBodyWriteFailed       func(*http.Request, string, int, error)
	ServiceCompleted              func(*http.Request, string)
}

type requestProcessingResultType uint8

const (
	BodyUnmarshalFailed requestProcessingResultType = iota + 1
	BodyValidationFailed
	HeaderParseFailed
	HeaderValidationFailed
	QueryParseFailed
	QueryValidationFailed
	PathParseFailed
	PathValidationFailed
	SecurityParseFailed
	SecurityCheckFailed
	ParseSucceed
)

type RequestProcessingResult struct {
	error error
	typee requestProcessingResultType
}

func NewRequestProcessingResult(t requestProcessingResultType, err error) RequestProcessingResult {
	return RequestProcessingResult{
		error: err,
		typee: t,
	}
}

func (r RequestProcessingResult) Type() requestProcessingResultType {
	return r.typee
}

func (r RequestProcessingResult) Err() error {
	return r.error
}

func CarsHandler(impl CarsService, r v5.Router, hooks *Hooks) http.Handler {
	router := &carsRouter{router: r, service: impl, hooks: hooks}

	router.mount()

	return router.router
}

type carsRouter struct {
	router  v5.Router
	service CarsService
	hooks   *Hooks
}

func (router *carsRouter) mount() {
	router.router.Get("/cars", router.GetCars)
}

func (router *carsRouter) parseGetCarsRequest(r *http.Request) (request GetCarsRequest) {
	request.ProcessingResult = RequestProcessingResult{typee: ParseSucceed}

	if router.hooks.RequestParseCompleted != nil {
		router.hooks.RequestParseCompleted(r, "GetCars")
	}

	return
}

func (router *carsRouter) GetCars(w http.ResponseWriter, r *http.Request) {
	defer r.Body.Close()

	response := router.service.GetCars(r.Context(), router.parseGetCarsRequest(r))

	if response.statusCode() == 302 && response.redirectURL() != "" {
		if router.hooks.RequestRedirectStarted != nil {
			router.hooks.RequestRedirectStarted(r, "GetCars", response.redirectURL())
		}

		http.Redirect(w, r, response.redirectURL(), 302)

		if router.hooks.ServiceCompleted != nil {
			router.hooks.ServiceCompleted(r, "GetCars")
		}

		return
	}

	for header, value := range response.headers() {
		w.Header().Set(header, value)
	}

	for _, c := range response.cookies() {
		cookie := c
		http.SetCookie(w, &cookie)
	}

	if router.hooks.RequestProcessingCompleted != nil {
		router.hooks.RequestProcessingCompleted(r, "GetCars")
	}

	if len(response.contentType()) > 0 {
		w.Header().Set("content-type", response.contentType())
	}

	w.WriteHeader(response.statusCode())

	if response.body() != nil {
		var (
			data []byte
			err  error
		)

		switch response.contentType() {
		case "application/xml":
			data, err = xml.Marshal(response.body())
		case "application/octet-stream":
			var ok bool
			if data, ok = (response.body()).([]byte); !ok {
				err = errors.New("body is not []byte")
			}
		case "text/html":
			data = []byte(fmt.Sprint(response.body()))
		case "application/json":
			fallthrough
		default:
			data, err = json.Marshal(response.body())
		}

		if err != nil {
			if router.hooks.ResponseBodyMarshalFailed != nil {
				router.hooks.ResponseBodyMarshalFailed(w, r, "GetCars", err)
			}

			return
		}

		if router.hooks.ResponseBodyMarshalCompleted != nil {
			router.hooks.ResponseBodyMarshalCompleted(r, "GetCars")
		}

		count, err := w.Write(data)
		if err != nil {
			if router.hooks.ResponseBodyWriteFailed != nil {
				router.hooks.ResponseBodyWriteFailed(r, "GetCars", count, err)
			}

			if router.hooks.ResponseBodyWriteCompleted != nil {
				router.hooks.ResponseBodyWriteCompleted(r, "GetCars", count)
			}

			return
		}

		if router.hooks.ResponseBodyWriteCompleted != nil {
			router.hooks.ResponseBodyWriteCompleted(r, "GetCars", count)
		}
	}

	if router.hooks.ServiceCompleted != nil {
		router.hooks.ServiceCompleted(r, "GetCars")
	}
}

type response struct {
	statusCode  int
	body        interface{}
	contentType string
	redirectURL string
	headers     map[string]string
	cookies     []http.Cookie
}

type responseInterface interface {
	statusCode() int
	body() interface{}
	contentType() string
	redirectURL() string
	cookies() []http.Cookie
	headers() map[string]string
}

type GetCarsResponse interface {
	responseInterface
	getCarsResponse()
}

type getCarsResponse struct {
	response
}

func (getCarsResponse) getCarsResponse() {}

func (response getCarsResponse) statusCode() int {
	return response.response.statusCode
}

func (response getCarsResponse) body() interface{} {
	return response.response.body
}

func (response getCarsResponse) contentType() string {
	return response.response.contentType
}

func (response getCarsResponse) redirectURL() string {
	return response.response.redirectURL
}

func (response getCarsResponse) headers() map[string]string {
	return response.response.headers
}

func (response getCarsResponse) cookies() []http.Cookie {
	return response.response.cookies
}

type getCarsStatusCodeResponseBuilder struct {
	response
}

func GetCarsResponseBuilder() *getCarsStatusCodeResponseBuilder {
	return new(getCarsStatusCodeResponseBuilder)
}

func (builder *getCarsStatusCodeResponseBuilder) StatusCode200() *getCars200ContentTypeBuilder {
	builder.response.statusCode = 200

	return &getCars200ContentTypeBuilder{response: builder.response}
}

type getCars200ContentTypeBuilder struct {
	response
}

type GetCars200ApplicationJsonResponseBuilder struct {
	response
}

func (builder *GetCars200ApplicationJsonResponseBuilder) Build() GetCarsResponse {
	return getCarsResponse{response: builder.response}
}

type GetCars200ApplicationXmlResponseBuilder struct {
	response
}

func (builder *GetCars200ApplicationXmlResponseBuilder) Build() GetCarsResponse {
	return getCarsResponse{response: builder.response}
}

func (builder *getCars200ContentTypeBuilder) ApplicationJson() *getCars200ApplicationJsonBodyBuilder {
	builder.response.contentType = "application/json"

	return &getCars200ApplicationJsonBodyBuilder{response: builder.response}
}

type getCars200ApplicationJsonBodyBuilder struct {
	response
}

func (builder *getCars200ApplicationJsonBodyBuilder) Body(body CarResponseApplicationjson) *GetCars200ApplicationJsonResponseBuilder {
	builder.response.body = body

	return &GetCars200ApplicationJsonResponseBuilder{response: builder.response}
}

func (builder *getCars200ContentTypeBuilder) ApplicationXml() *getCars200ApplicationXmlBodyBuilder {
	builder.response.contentType = "application/xml"

	return &getCars200ApplicationXmlBodyBuilder{response: builder.response}
}

type getCars200ApplicationXmlBodyBuilder struct {
	response
}

func (builder *getCars200ApplicationXmlBodyBuilder) Body(body CarResponseApplicationxml) *GetCars200ApplicationXmlResponseBuilder {
	builder.response.body = body

	return &GetCars200ApplicationXmlResponseBuilder{response: builder.response}
}

type CarsService interface {
	GetCars(context.Context, GetCarsRequest) GetCarsResponse
}

type GetCarsRequest struct {
	ProcessingResult RequestProcessingResult
}

type SecurityScheme string

const ()

type securityProcessor struct {
	scheme  SecurityScheme
	extract func(r *http.Request) (string, string, bool)
	handle  func(r *http.Request, scheme SecurityScheme, name string, value string) error
}

var securityExtractorsFuncs = map[SecurityScheme]func(r *http.Request) (string, string, bool){}

type SecuritySchemas interface{}

type SecurityCheckResult struct {
	Scheme SecurityScheme
	Value  string
}
