// This file is generated by github.com/common-fate/go-oas3. DO NOT EDIT.

package output

import "encoding/json"

type carResponse struct {
	ID string `json:"id"`
}

type CarResponse struct {
	ID string `json:"id"`
}

func (body *CarResponse) UnmarshalJSON(data []byte) error {
	var value carResponse
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}

	body.ID = value.ID

	return nil
}
func (body CarResponse) Validate() error {
	return nil
}
